--
-- File generated with SQLiteStudio v3.2.1 on 周三 4月 3 20:43:59 2019
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: keys
CREATE TABLE keys ("key" VARCHAR (500) PRIMARY KEY UNIQUE NOT NULL, name VARCHAR (500) NOT NULL, type VARCHAR (50) NOT NULL, norm VARCHAR (100), unit VARCHAR (20), units VARCHAR (100), note VARCHAR (500), "explain" TEXT, remark TEXT, creator VARCHAR (50) DEFAULT sys, create_date DATETIME DEFAULT (datetime()), updator VARCHAR (50) DEFAULT sys, update_date DATETIME DEFAULT (datetime()));
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('bmi_bsa', 'Body Mass Index (BMI) and Body Surface Area (BSA)', 'ss', NULL, 'points', NULL, NULL, '身高体重比', NULL, 'sys', NULL, 'sys', NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('height', '身高', 'item', NULL, 'cm', NULL, NULL, '身高', NULL, 'sys', NULL, 'sys', NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('weight', '体重', 'item', NULL, 'kg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('bmi', 'bmi', 'item', NULL, 'kg/m^2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('bsa', 'BSA', 'item', NULL, 'm^2', NULL, NULL, NULL, 'Body SurFace Area', NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('age', '年龄', 'item', NULL, 'years', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'APACHE II Score', 'ss', NULL, 'points', NULL, 'APACHE-II评分提供了一个基于多个实验室值和患者体征的ICU死亡率估计，同时考虑了急性和慢性疾病。注:所使用的数据应来自ICU的最初24小时，且应使用最差值(较基线/正常值更远)', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('severe_organ_failure_or_immunocompromise', '严重器官衰竭或免疫功能损害史', 'item', NULL, NULL, NULL, NULL, '心力衰竭IV类，肝硬化，慢性肺病，或透析依赖', NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('no', 'No', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('yes', 'Yes', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('type_of_surgery', '手术方式', 'item', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('emergency_postoperative ', '急诊手术', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('elective_postoperative ', '择期手术', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('nonperative', '非手术', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('temperature', '体温', 'item', NULL, '°C', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('mean_arterial_pressure', '平均动脉压', 'item', NULL, 'mm Hg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('arterial_ph', '动脉血pH', 'item', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('heart_rate', '心率/脉冲', 'item', NULL, 'beats/min', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('respiratory_rate', '呼吸频率', 'item', NULL, 'breaths/min', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('serum_sodium', '血钠', 'item', NULL, 'mmol/L', NULL, NULL, NULL, '血清钠', NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('serum_potassium', '血钾', 'item', NULL, 'mmol/L', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('serum_creatinine', '血肌酐', 'item', NULL, 'mg/100ml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('hematocrit', '血细胞压积', 'item', '36 - 51', '%', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('white_blood_cell_count', '白细胞计数', 'item', '3.7 - 10.7', 'x10^9 cells/L', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('fio2', 'FiO2', 'item', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('lt50percentum', '<50%', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('gte50percentum', '≥50%', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('pao2', '动脉氧分压', 'item', NULL, 'mm Hg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('gt70', '>70', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('61-70', '61-70', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('55-60', '55-60', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('lt55', '<55', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('A-a_O2_gradient', '氧合评分', 'ss', '3 - 15', 'points', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('glasgow_coma_scale', '格拉斯哥昏迷量表', 'ss', NULL, 'points', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('350-499', '350-499', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('200-349', '200-349', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('lt200', '<200', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('gt499', '>499', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('acute_renal_failure', '急性肾功能衰竭', 'item', NULL, NULL, NULL, '"acute renal failure" was not defined in the original study. Use clinical judgment to determine whether patient has acute kidney injury.', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('lt50percentum_or_non-intubated', '<50%(or non-intubated)', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('rectal_temperature', '直肠温度', 'option', NULL, '°C', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('eye_response', '眼部反应', 'item', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('verbal_response', '语言反应', 'item', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('motor_response', '运动反应', 'item', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('to_verbal_command ', '声音刺激后睁眼', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('spontaneously', '可自动睁眼', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('not_assessable ', '不可评估的', 'option', NULL, NULL, NULL, '不可评估(外伤、水肿等)', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('no_eye_opening', '无反应', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('to_pain', '疼痛刺激后睁眼', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('oriented', '回答正确', 'option', NULL, NULL, NULL, '导向的', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('confused', '回答错误，迷糊', 'option', NULL, NULL, NULL, '迷糊的', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('incomprehensible_sounds', '只能发音', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('inappropriate_words', '语句不清', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('no_verbal_response ', '没有言语反应', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('intubated', '少儿', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('extension_to_pain', '刺痛时肢体过伸', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('flexion _to_pain ', '刺痛时肢体屈曲', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('withdrawal_from_pain ', '刺痛躲避', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('localizes_pain', '指出疼痛部位', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('obeys_commands', '服从命令', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('no_motor_response', '没有肢体反应', 'option', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('atmospheric_pressure', '大气压强', 'item', NULL, 'mm Hg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('paco2', 'PaCO?', 'item', NULL, 'mm Hg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO keys ("key", name, type, norm, unit, units, note, "explain", remark, creator, create_date, updator, update_date) VALUES ('expected_a_a_gradient_for_age', 'Expected A-a Gradient for Age', 'item', NULL, 'mm Hg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Table: ss
CREATE TABLE ss ("key" VARCHAR (500) PRIMARY KEY UNIQUE NOT NULL REFERENCES keys ("key"), remark TEXT, creator VARCHAR (50) DEFAULT sys, create_date DATETIME DEFAULT (datetime()), updator VARCHAR (50) DEFAULT sys, update_date DATETIME DEFAULT (datetime()));
INSERT INTO ss ("key", remark, creator, create_date, updator, update_date) VALUES ('bmi_bsa', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss ("key", remark, creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'APACHE II Score', NULL, NULL, NULL, NULL);
INSERT INTO ss ("key", remark, creator, create_date, updator, update_date) VALUES ('glasgow_coma_scale', 'Glasgow Coma Scale/Score', NULL, NULL, NULL, NULL);
INSERT INTO ss ("key", remark, creator, create_date, updator, update_date) VALUES ('A-a_O2_gradient', 'A-a O? Gradient', NULL, NULL, NULL, NULL);

-- Table: ss_formulas
CREATE TABLE ss_formulas ("key" VARCHAR (500) REFERENCES keys ("key") NOT NULL, ss_key VARCHAR (500) REFERENCES ss ("key") NOT NULL, js_formulas TEXT, remark TEXT, creator VARCHAR (50) DEFAULT sys, create_date DATETIME DEFAULT (datetime()), updator VARCHAR (50) DEFAULT sys, update_date DATETIME DEFAULT (datetime()));
INSERT INTO ss_formulas ("key", ss_key, js_formulas, remark, creator, create_date, updator, update_date) VALUES ('bmi', 'bmi_bsa', 'weight/Math.pow(height,2)', 'Body mass index, kg/m2 = weight, kg / (height, m)2', NULL, NULL, NULL, NULL);
INSERT INTO ss_formulas ("key", ss_key, js_formulas, remark, creator, create_date, updator, update_date) VALUES ('bsa', 'bmi_bsa', 'Math.pow(weight*height/3600,0.5)', 'Body surface area (the Mosteller formula), m2 = [ Height, cm x Weight, kg  / 3600 ]1/2', NULL, NULL, NULL, NULL);
INSERT INTO ss_formulas ("key", ss_key, js_formulas, remark, creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '+', '所有分值相加', NULL, NULL, NULL, NULL);
INSERT INTO ss_formulas ("key", ss_key, js_formulas, remark, creator, create_date, updator, update_date) VALUES ('glasgow_coma_scale', 'glasgow_coma_scale', 'eye_response+verbal_response+motor_response', '所有分值相加', NULL, NULL, NULL, NULL);
INSERT INTO ss_formulas ("key", ss_key, js_formulas, remark, creator, create_date, updator, update_date) VALUES ('A-a_O2_gradient', 'A-a_O2_gradient', '""', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_formulas ("key", ss_key, js_formulas, remark, creator, create_date, updator, update_date) VALUES ('expected_a_a_gradient_for_age', 'A-a_O2_gradient', '(age/4)+4', NULL, NULL, NULL, NULL, NULL);

-- Table: ss_items
CREATE TABLE ss_items ("key" VARCHAR (500) REFERENCES keys ("key") NOT NULL, p_key VARCHAR (500) REFERENCES keys ("key"), ss_key VARCHAR (500) REFERENCES ss ("key") NOT NULL, "when" VARCHAR (500) REFERENCES keys ("key"), when_eq VARCHAR (500) REFERENCES keys ("key"), remark TEXT, creator VARCHAR (50) DEFAULT sys, create_date DATETIME DEFAULT (datetime()), update_date DATETIME DEFAULT (datetime()), updator VARCHAR (50) DEFAULT sys);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('weight', NULL, 'bmi_bsa', NULL, NULL, NULL, NULL, NULL, NULL, 'sys');
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('height', NULL, 'bmi_bsa', NULL, NULL, NULL, NULL, NULL, NULL, 'sys');
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('age', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, 'sys');
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('type_of_surgery', NULL, 'ss_apacheii', 'severe_organ_failure_or_immunocompromise', 'yes', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('no', 'severe_organ_failure_or_immunocompromise', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('yes', 'severe_organ_failure_or_immunocompromise', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('severe_organ_failure_or_immunocompromise', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('emergency_postoperative ', 'type_of_surgery', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('elective_postoperative ', 'type_of_surgery', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('nonperative', 'type_of_surgery', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('rectal_temperature', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('mean_arterial_pressure', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('arterial_ph', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('heart_rate', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('respiratory_rate', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('serum_sodium', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('serum_potassium', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('serum_creatinine', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('acute_renal_failure', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('no', 'acute_renal_failure', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('yes', 'acute_renal_failure', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('hematocrit', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('white_blood_cell_count', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('glasgow_coma_scale', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('fio2', NULL, 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('gte50percentum', 'fio2', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('lt50percentum_or_non-intubated', 'fio2', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('A-a_O2_gradient', NULL, 'ss_apacheii', 'fio2', 'gte50percentum', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('pao2', NULL, 'ss_apacheii', 'fio2', 'lt50percentum_or_non-intubated', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('lt200', 'A-a_O2_gradient', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('200-349', 'A-a_O2_gradient', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('350-499', 'A-a_O2_gradient', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('gt499', 'A-a_O2_gradient', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('gt70', 'pao2', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('61-70', 'pao2', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('55-60', 'pao2', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('lt55', 'pao2', 'ss_apacheii', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('motor_response', NULL, 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('verbal_response', NULL, 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('eye_response', NULL, 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('no_motor_response', 'motor_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('extension_to_pain', 'motor_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('flexion _to_pain ', 'motor_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('withdrawal_from_pain ', 'motor_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('localizes_pain', 'motor_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('obeys_commands', 'motor_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('intubated', 'verbal_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('no_verbal_response ', 'verbal_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('inappropriate_words', 'verbal_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('incomprehensible_sounds', 'verbal_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('confused', 'verbal_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('oriented', 'verbal_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('to_pain', 'eye_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('to_verbal_command ', 'eye_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('spontaneously', 'eye_response', 'glasgow_coma_scale', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('age', NULL, 'A-a_O2_gradient', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('fio2', NULL, 'A-a_O2_gradient', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('pao2', NULL, 'A-a_O2_gradient', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('atmospheric_pressure', NULL, 'A-a_O2_gradient', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_items ("key", p_key, ss_key, "when", when_eq, remark, creator, create_date, update_date, updator) VALUES ('paco2', NULL, 'A-a_O2_gradient', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Table: ss_scores
CREATE TABLE ss_scores ("key" VARCHAR (500) NOT NULL REFERENCES keys ("key"), ss_key VARCHAR (500) REFERENCES ss ("key"), value VARCHAR (500) NOT NULL, score VARCHAR (100), type VARCHAR (50), result VARCHAR (100), remark TEXT, "explain" TEXT, creator VARCHAR (50) DEFAULT sys, create_date DATETIME DEFAULT (datetime()), updator VARCHAR (50) DEFAULT sys, update_date DATETIME DEFAULT (datetime()));
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('age', 'ss_apacheii', '≤44', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('age', 'ss_apacheii', '45-54', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('age', 'ss_apacheii', '55-64', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('age', 'ss_apacheii', '65-74', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('age', 'ss_apacheii', '>74', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('bmi', 'bmi_bsa', '18.5–24.9', NULL, NULL, '正常', '正常', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('bmi', 'bmi_bsa', '>18.5', NULL, NULL, '偏轻', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('bmi', 'bmi_bsa', '25.0–29.9', NULL, NULL, '偏胖', NULL, NULL, 'sys', '2019-04-01 03:32:27', 'sys', '2019-04-01 03:32:27');
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('bmi', 'bmi_bsa', '30.0–34.9', NULL, NULL, '肥胖-一级', NULL, NULL, 'sys', '2019-04-01 03:33:54', 'sys', '2019-04-01 03:33:54');
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('bmi', 'bmi_bsa', '35.0–39.9', NULL, NULL, '肥胖-二级', NULL, NULL, 'sys', '2019-04-01 03:34:21', 'sys', '2019-04-01 03:34:21');
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('bmi', 'bmi_bsa', '≥40.0', NULL, NULL, '肥胖-三级', NULL, NULL, 'sys', '2019-04-01 03:35:15', 'sys', '2019-04-01 03:35:15');
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('severe_organ_failure_or_immunocompromise', 'ss_apacheii', 'yes', '', NULL, NULL, '需要子项目', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('severe_organ_failure_or_immunocompromise', 'ss_apacheii', 'no', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('type_of_surgery', 'ss_apacheii', 'elective_postoperative ', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('type_of_surgery', 'ss_apacheii', 'emergency_postoperative|nonperative', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('rectal_temperature', 'ss_apacheii', '≥41', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('rectal_temperature', 'ss_apacheii', '39-<41', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('rectal_temperature', 'ss_apacheii', '38.5-<39', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('rectal_temperature', 'ss_apacheii', '36-<38.5', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('rectal_temperature', 'ss_apacheii', '34-<36', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('rectal_temperature', 'ss_apacheii', '32-<34', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('rectal_temperature', 'ss_apacheii', '30-<32', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('rectal_temperature', 'ss_apacheii', '<30', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('mean_arterial_pressure', 'ss_apacheii', '≤49', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('mean_arterial_pressure', 'ss_apacheii', '49<-69', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('mean_arterial_pressure', 'ss_apacheii', '69<-109', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('mean_arterial_pressure', 'ss_apacheii', '109<-129', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('mean_arterial_pressure', 'ss_apacheii', '129<-159', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('mean_arterial_pressure', 'ss_apacheii', '>159', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('heart_rate', 'ss_apacheii', '≥180', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('heart_rate', 'ss_apacheii', '140-<180', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('heart_rate', 'ss_apacheii', '70-<110', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('heart_rate', 'ss_apacheii', '110-<140', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('heart_rate', 'ss_apacheii', '<40', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('heart_rate', 'ss_apacheii', '40-<55', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('heart_rate', 'ss_apacheii', '55-<70', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('respiratory_rate', 'ss_apacheii', '<6', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('respiratory_rate', 'ss_apacheii', '6-<10', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('respiratory_rate', 'ss_apacheii', '10-<12', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('respiratory_rate', 'ss_apacheii', '12-<25', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('respiratory_rate', 'ss_apacheii', '25-<35', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('respiratory_rate', 'ss_apacheii', '35-<50', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('respiratory_rate', 'ss_apacheii', '≥50', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('A-a_O2_gradient', 'ss_apacheii', '350-499', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('A-a_O2_gradient', 'ss_apacheii', 'gt499', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('A-a_O2_gradient', 'ss_apacheii', '200-349', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('A-a_O2_gradient', 'ss_apacheii', 'lt200', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('pao2', 'ss_apacheii', 'lt55', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('pao2', 'ss_apacheii', '55-60', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('pao2', 'ss_apacheii', '61-70', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('pao2', 'ss_apacheii', 'gt70', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('arterial_ph', 'ss_apacheii', '<7.15', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('arterial_ph', 'ss_apacheii', '7.15-<7.25', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('arterial_ph', 'ss_apacheii', '7.25-<7.33', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('arterial_ph', 'ss_apacheii', '7.33-<7.50', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('arterial_ph', 'ss_apacheii', '7.50-<7.60', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('arterial_ph', 'ss_apacheii', '7.60-<7.70', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('arterial_ph', 'ss_apacheii', '≥7.70', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_sodium', 'ss_apacheii', '<111', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_sodium', 'ss_apacheii', '111-<120', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_sodium', 'ss_apacheii', '120-<130', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_sodium', 'ss_apacheii', '130-<150', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_sodium', 'ss_apacheii', '150-<155', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_sodium', 'ss_apacheii', '155-<160', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_sodium', 'ss_apacheii', '160-<180', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_sodium', 'ss_apacheii', '≥180', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_potassium', 'ss_apacheii', '<2.5', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_potassium', 'ss_apacheii', '2.5-<3.0', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_potassium', 'ss_apacheii', '3.0-<3.5', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_potassium', 'ss_apacheii', '3.5-<5.5', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_potassium', 'ss_apacheii', '5.5-<6.0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_potassium', 'ss_apacheii', '6.0-<7.0', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_potassium', 'ss_apacheii', '≥7.0', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_creatinine', 'ss_apacheii', '<0.6', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_creatinine', 'ss_apacheii', '0.6-<1.5', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_creatinine', 'ss_apacheii', '1.5-<2.0 and acute_renal_failure=no', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_creatinine', 'ss_apacheii', '2.0-<3.5 and acute_renal_failure=no', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_creatinine', 'ss_apacheii', '1.5-<2.0 and acute_renal_failure=yes', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_creatinine', 'ss_apacheii', '≥3.5 and acute_renal_failure=no', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_creatinine', 'ss_apacheii', '2.0-<3.5 and acute_renal_failure=yes', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('serum_creatinine', 'ss_apacheii', '≥3.5 and acute_renal_failure=yes', '8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('hematocrit', 'ss_apacheii', '<20', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('hematocrit', 'ss_apacheii', '20-<30', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('hematocrit', 'ss_apacheii', '30-<46', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('hematocrit', 'ss_apacheii', '46-<50', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('hematocrit', 'ss_apacheii', '50-<60', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('hematocrit', 'ss_apacheii', '≥60', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('white_blood_cell_count', 'ss_apacheii', '<1', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('white_blood_cell_count', 'ss_apacheii', '1-<3', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('white_blood_cell_count', 'ss_apacheii', '3-<15', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('white_blood_cell_count', 'ss_apacheii', '15-<20', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('white_blood_cell_count', 'ss_apacheii', '20-<40', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('white_blood_cell_count', 'ss_apacheii', '≥40', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('glasgow_coma_scale', 'ss_apacheii', '1-15', '15-this', NULL, NULL, '需要计算', NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '5-9', '8%', 'nonoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '0-4', '4%', 'nonoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '>34', '85%', 'nonoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '30-34', '73%', 'nonoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '25-29', '55%', 'nonoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '20-24', '40%', 'nonoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '15-19', '25%', 'nonoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '10-14', '15%', 'nonoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '>34', '88%', 'postoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '30-34', '73%', 'postoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '25-29', '35%', 'postoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '20-24', '30%', 'postoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '15-19', '12%', 'postoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '10-14', '7%', 'postoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '5-9', '3%', 'postoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('ss_apacheii', 'ss_apacheii', '0-4', '1%', 'postoperative', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('eye_response', 'glasgow_coma_scale', 'not_assessable', '1c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('eye_response', 'glasgow_coma_scale', 'no_eye_opening', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('eye_response', 'glasgow_coma_scale', 'to_pain', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('eye_response', 'glasgow_coma_scale', 'to_verbal_command ', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('eye_response', 'glasgow_coma_scale', 'spontaneously', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('verbal_response', 'glasgow_coma_scale', 'intubated', '1t', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('verbal_response', 'glasgow_coma_scale', 'no_verbal_response', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('verbal_response', 'glasgow_coma_scale', 'incomprehensible_sounds', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('verbal_response', 'glasgow_coma_scale', 'inappropriate_words', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('verbal_response', 'glasgow_coma_scale', 'confused', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('verbal_response', 'glasgow_coma_scale', 'oriented', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('motor_response', 'glasgow_coma_scale', 'no_motor_response', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('motor_response', 'glasgow_coma_scale', 'extension_to_pain', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('motor_response', 'glasgow_coma_scale', 'flexion_to_pain', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('motor_response', 'glasgow_coma_scale', 'withdrawal_from_pain', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('motor_response', 'glasgow_coma_scale', 'localizes_pain', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('motor_response', 'glasgow_coma_scale', 'obeys_commands', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ss_scores ("key", ss_key, value, score, type, result, remark, "explain", creator, create_date, updator, update_date) VALUES ('fio2', 'ss_apacheii', 'gte50percentum|lt50percentum_or_non-intubated', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Index: key
CREATE INDEX "key" ON ss_formulas ("key", ss_key);

-- View: v_formulas
CREATE VIEW v_formulas AS select s.key,k.name,s.ss_key,s.js_formulas,k.norm,k.note,k."explain",k.unit,k.units,(case when s.remark then s.remark else k.remark end) as remark
from ss_formulas s
left join keys k on s.key=k.key;

-- View: v_items
CREATE VIEW v_items AS select s.key,k.name,s.p_key,s.ss_key,s."when",s.when_eq,k.type,k.norm,k.unit,k.units,k.note,k."explain",(case when s.remark then s.remark else k.remark end) as remark
from ss_items s
left join keys k on s.key=k.key;

-- View: v_ss
CREATE VIEW v_ss AS select s.key,k.name,k.norm,k.note,k."explain",(case when s.remark then s.remark else k.remark end) as remark
from ss s 
left join keys k on s.key=k.key;

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
